# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180728_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='submit_answer',
            field=models.BooleanField(default=False),
        ),
    ]
