# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_answers_submit_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='submit_answer',
            field=models.IntegerField(default=0),
        ),
    ]
